### ISSUE TITLE
The question about cell_type_proportion.csv in data

### ISSUE THREAD

**Issue by tqwang743** [lichen2018/stVAE#1]
Hi lichen,

It is a fantastic method for analyzing spatial transcriptomics!

I tried to apply the mouse brain data you provide to my own model, but I find that there are no specific cell type name in the columns of cell_type_proportion.csv and no specific spot name in the rows of cell_type_proportion.csv.  So I can not calculate the JSD between the results I predict and grountruth . I would appreciate it if you could give me the dataset with more definitive information. I am looking forward to you giving me some solutions and suggestions to the difficulties I meet.
 
Thank you very much! 

best,
tqwang

**Comment by lichen2018** [comment]
Dear tqwang743,
Have you run the code: `model, cell_type_list = train_stVAE()`, the cell type names in the columns of cell_type_proportion.csv is the same as cell_type_list.
The  specific spot names in the rows of cell_type_proportion.csv should be the same as the obs_names in your spatial transcriptomic anndata file.

**Comment by lichen2018** [comment]
> Hi lichen,
> 
> It is a fantastic method for analyzing spatial transcriptomics!
> 
> I tried to apply the mouse brain data you provide to my own model, but I find that there are no specific cell type name in the columns of cell_type_proportion.csv and no specific spot name in the rows of cell_type_proportion.csv. So I can not calculate the JSD between the results I predict and grountruth . I would appreciate it if you could give me the dataset with more definitive information. I am looking forward to you giving me some solutions and suggestions to the difficulties I meet.
> 
> Thank you very much!
> 
> best, tqwang

Dear tqwang743,
Have you run the code: model, cell_type_list = train_stVAE(), the cell type names in the columns of cell_type_proportion.csv is the same as cell_type_list.
The specific spot names in the rows of cell_type_proportion.csv should be the same as the obs_names in your spatial transcriptomic anndata file.

**Comment by lichen2018** [comment]
> Hi lichen,
> 
> It is a fantastic method for analyzing spatial transcriptomics!
> 
> I tried to apply the mouse brain data you provide to my own model, but I find that there are no specific cell type name in the columns of cell_type_proportion.csv and no specific spot name in the rows of cell_type_proportion.csv. So I can not calculate the JSD between the results I predict and grountruth . I would appreciate it if you could give me the dataset with more definitive information. I am looking forward to you giving me some solutions and suggestions to the difficulties I meet.
> 
> Thank you very much!
> 
> best, tqwang

Dear tqwang743,
Have you run the code: model, cell_type_list = train_stVAE() ? the cell_type_list is the  column names of cell_type_proportion.csv.
The specific spot names in the rows of cell_type_proportion.csv should be the same as the obs_names in your spatial transcriptomic anndata file.

**Comment by lichen2018** [comment]
> Hi lichen,
> 
> It is a fantastic method for analyzing spatial transcriptomics!
> 
> I tried to apply the mouse brain data you provide to my own model, but I find that there are no specific cell type name in the columns of cell_type_proportion.csv and no specific spot name in the rows of cell_type_proportion.csv. So I can not calculate the JSD between the results I predict and grountruth . I would appreciate it if you could give me the dataset with more definitive information. I am looking forward to you giving me some solutions and suggestions to the difficulties I meet.
> 
> Thank you very much!
> 
> best, tqwang

Dear tqwang743,
Do your mean the cell_type_proportion.csv of mouse brain using slide-seqV2? the cell_type_proportion.csv has been updated. Thanks!

**Comment by tqwang743** [comment]
Yes, I have found cell_type_proportion.csv you update, thank you very much for your help !

**Comment by lichen2018** [comment]
> Yes, I have found cell_type_proportion.csv you update, thank you very much for your help !

No problem.

**Comment by lichen2018** [comment]
> Yes, I have found cell_type_proportion.csv you update, thank you very much for your help !

No problem.
